// Persistent experience -- the thing that makes "learning" an accurate word.
//
// Until now every improvement came from a human reading telemetry and changing
// code. The agent's own memory was a rolling window that died at restart, so
// it re-made the same mistake on every run, forever.
//
// This is deliberately DETERMINISTIC learning. Nothing here is generated by a
// model: it records what was actually tried, what actually failed, and where
// the bot actually got hurt, then feeds that back into the next decision. That
// makes it verifiable -- every lesson traces to counted events -- and immune to
// the failure mode where a model invents a confident lesson from noise.
//
// LLM-authored lessons (from reflect.py) are a separate, reviewed path. They
// do not belong here, because a wrong lesson that persists is worse than no
// lesson at all.

import fs from 'node:fs'
import path from 'node:path'
import { config } from './config.mjs'
import { log } from './logger.mjs'

const SCHEMA = 1
const MAX_AVOID = 40
const MAX_SITES = 30
// A lesson learned six hours ago about a tree that has since been chopped down
// is noise. Decay keeps memory relevant without unbounded growth.
const DECAY_MS = 6 * 60 * 60 * 1000
const HAZARD_RADIUS = 12

const key = (skill, args) => `${skill}:${JSON.stringify(args ?? {})}`

export class Lessons {
  constructor(file) {
    this.file = file
    this.data = { schema: SCHEMA, avoid: {}, worked: {}, sites: [], runs: 0, progress: {} }
    this.dirty = false
    this.#load()
  }

  #load() {
    try {
      const raw = JSON.parse(fs.readFileSync(this.file, 'utf8'))
      if (raw.schema === SCHEMA) this.data = raw
      else log('warn', 'lessons: schema changed, starting fresh', { was: raw.schema })
    } catch { /* first run */ }
    this.data.runs = (this.data.runs ?? 0) + 1
    this.#prune()
    this.dirty = true
    log('info', 'lessons loaded', {
      run: this.data.runs,
      avoid: Object.keys(this.data.avoid).length,
      worked: Object.keys(this.data.worked).length,
      hazard_sites: this.data.sites.length,
    })
  }

  #prune() {
    const now = Date.now()
    for (const [k, v] of Object.entries(this.data.avoid)) {
      // Halve the count rather than dropping outright: something that failed
      // ten times last week is still weak evidence, not zero evidence.
      if (now - (v.last ?? 0) > DECAY_MS) {
        v.fails = Math.floor(v.fails / 2)
        if (v.fails < 2) delete this.data.avoid[k]
      }
    }
    for (const s of this.data.sites) {
      if (now - (s.last ?? 0) > DECAY_MS) s.count = Math.floor(s.count / 2)
    }
    this.data.sites = this.data.sites.filter(s => s.count >= 2).slice(-MAX_SITES)

    const avoid = Object.entries(this.data.avoid)
      .sort((a, b) => b[1].fails - a[1].fails).slice(0, MAX_AVOID)
    this.data.avoid = Object.fromEntries(avoid)
  }

  save() {
    if (!this.dirty) return
    try {
      fs.mkdirSync(path.dirname(this.file), { recursive: true })
      fs.writeFileSync(this.file, JSON.stringify(this.data, null, 1))
      this.dirty = false
    } catch (e) {
      log('error', 'lessons: save failed', { err: e.message })
    }
  }

  // ------------------------------------------------------------ recording --

  recordFailure(skill, args, failClass, pos) {
    const k = key(skill, args)
    const e = this.data.avoid[k] ?? { skill, args, fails: 0, classes: {} }
    e.fails++
    e.last = Date.now()
    e.classes[failClass ?? 'other'] = (e.classes[failClass ?? 'other'] ?? 0) + 1
    if (pos) e.where = { x: Math.round(pos.x), y: Math.round(pos.y), z: Math.round(pos.z) }
    this.data.avoid[k] = e
    this.dirty = true
  }

  recordSuccess(skill, args) {
    const k = key(skill, args)
    const e = this.data.worked[k] ?? { skill, args, wins: 0 }
    e.wins++; e.last = Date.now()
    this.data.worked[k] = e
    // Success is evidence against an existing avoid rule, so weaken it rather
    // than letting one old failure suppress a now-working action forever.
    if (this.data.avoid[k]) {
      this.data.avoid[k].fails--
      if (this.data.avoid[k].fails <= 0) delete this.data.avoid[k]
    }
    this.dirty = true
  }

  /** Somewhere the bot drowned, got entombed, got stuck, or died. */
  recordHazard(kind, pos) {
    if (!pos) return
    const near = this.data.sites.find(s =>
      s.kind === kind && Math.hypot(s.x - pos.x, s.z - pos.z) < HAZARD_RADIUS &&
      Math.abs(s.y - pos.y) < 8)
    if (near) { near.count++; near.last = Date.now() }
    else {
      this.data.sites.push({
        kind, x: Math.round(pos.x), y: Math.round(pos.y), z: Math.round(pos.z),
        count: 1, last: Date.now(),
      })
    }
    this.dirty = true
  }

  // ------------------------------------------------------------- applying --

  /**
   * Milestone progress, carried across restarts.
   *
   * Deliberately stores what the bot GAVE UP ON and how hard it has tried --
   * never which milestones are complete. Completion is re-derived from actual
   * world state on every start, because inventory can be lost to death and a
   * restored "done" would claim work the world cannot back up. A proven-
   * unreachable goal, by contrast, stays unreachable across a restart, and
   * re-attempting it from scratch every run is exactly the forever-loop this
   * file exists to end.
   */
  getProgress() {
    const p = this.data.progress ?? {}
    return { attempts: p.attempts ?? {}, skipped: p.skipped ?? [] }
  }

  setProgress(attempts, skipped) {
    // MERGE. Assigning a fresh object here dropped the sibling `blocked` key
    // that bumpBlocked() maintains -- and since this runs after every decision,
    // it wiped the probation countdown on every cycle, silently undoing the
    // persistence it was added to provide. The counter never climbed past 1.
    const p = (this.data.progress ??= {})
    p.attempts = attempts
    p.skipped = skipped
    this.dirty = true
  }

  /**
   * Count one probation block and report the running total.
   *
   * Lives here, not in AdmissionControl, because a reconnect builds a fresh
   * controller. Scout01 reached run=12 in under an hour -- every socketClosed
   * reset an in-memory tally to zero, so a 1-in-5 probation never reached 5
   * and the block stayed permanent exactly as before the fix. Third time today
   * that a counter which had to outlive the process was kept in memory.
   */
  bumpBlocked(k) {
    const p = (this.data.progress ??= {})
    p.blocked ??= {}
    p.blocked[k] = (p.blocked[k] ?? 0) + 1
    this.dirty = true
    return p.blocked[k]
  }

  /** How many times this exact action has failed, across ALL runs. */
  failCount(skill, args) {
    return this.data.avoid[key(skill, args)]?.fails ?? 0
  }

  /** Hazard sites within range of a point, worst first. */
  hazardsNear(pos, radius = 40) {
    if (!pos) return []
    return this.data.sites
      .filter(s => Math.hypot(s.x - pos.x, s.z - pos.z) <= radius && s.count >= 2)
      .sort((a, b) => b.count - a.count)
  }

  /**
   * The lines injected into the prompt. Kept short and concrete -- a wall of
   * history crowds out current world state, which is worth more.
   */
  promptLines(pos, limit = 6) {
    const out = []
    const worst = Object.values(this.data.avoid)
      .filter(e => e.fails >= 2)
      .sort((a, b) => b.fails - a.fails)
      .slice(0, limit)
    for (const e of worst) {
      const why = Object.entries(e.classes).sort((a, b) => b[1] - a[1])[0]?.[0] ?? 'failed'
      out.push(`${e.skill}(${JSON.stringify(e.args)}) has failed ${e.fails}x across runs — usually "${why}"`)
    }
    for (const s of this.hazardsNear(pos, 60).slice(0, 3)) {
      out.push(`${s.kind} happened ${s.count}x near ${s.x},${s.y},${s.z} — avoid that area`)
    }
    const best = Object.values(this.data.worked)
      .filter(e => e.wins >= 3).sort((a, b) => b.wins - a.wins).slice(0, 2)
    for (const e of best) {
      out.push(`${e.skill}(${JSON.stringify(e.args)}) has worked ${e.wins}x — a reliable choice`)
    }
    return out
  }

  get stats() {
    return {
      run: this.data.runs,
      avoid: Object.keys(this.data.avoid).length,
      worked: Object.keys(this.data.worked).length,
      sites: this.data.sites.length,
    }
  }
}

export function openLessons() {
  return new Lessons(path.join(config.log.stateDir, `lessons-${config.bot.name}.json`))
}
