// Persistent experience -- the thing that makes "learning" an accurate word.
//
// Until now every improvement came from a human reading telemetry and changing
// code. The agent's own memory was a rolling window that died at restart, so
// it re-made the same mistake on every run, forever.
//
// This is deliberately DETERMINISTIC learning. Nothing here is generated by a
// model: it records what was actually tried, what actually failed, and where
// the bot actually got hurt, then feeds that back into the next decision. That
// makes it verifiable -- every lesson traces to counted events -- and immune to
// the failure mode where a model invents a confident lesson from noise.
//
// LLM-authored lessons (from reflect.py) are a separate, reviewed path. They
// do not belong here, because a wrong lesson that persists is worse than no
// lesson at all.

import fs from 'node:fs'
import path from 'node:path'
import { config } from './config.mjs'
import { log } from './logger.mjs'
import { actionKey } from './skills.mjs'

const SCHEMA = 1
const MAX_AVOID = 40
const MAX_SITES = 30
// A lesson learned six hours ago about a tree that has since been chopped down
// is noise. Decay keeps memory relevant without unbounded growth.
const DECAY_MS = 6 * 60 * 60 * 1000
const HAZARD_RADIUS = 12
const FORGET_MS = 20 * 60 * 1000   // one failure forgiven per 20 idle minutes

const key = actionKey   // ONE definition, shared with the admission gate

export class Lessons {
  constructor(file, shared = false) {
    this.shared = shared
    // Keys this bot has itself recorded a failure for. Provenance must reflect
    // who OBSERVED a failure, not who happened to load the file afterwards.
    this.touched = new Set()
    this.file = file
    this.data = { schema: SCHEMA, avoid: {}, worked: {}, sites: [], runs: 0, progress: {}, skillVersions: {} }
    this.dirty = false
    this.savesSincePrune = 0
    this.#load()
  }

  /** Merge our deltas into whatever peers have written since we loaded. */
  #saveMerged() {
    let cur = { schema: SCHEMA, avoid: {}, worked: {}, sites: [], runs: 0,
                progress: {}, skillVersions: {} }
    try {
      const raw = JSON.parse(fs.readFileSync(this.file, 'utf8'))
      if (raw.schema === SCHEMA) cur = raw
    } catch { /* first write */ }

    // avoid: keep the HIGHER fail count and union the class tallies.
    //
    // Max here guards against one bot's concurrent writes double-counting. It
    // does NOT stop a hive accumulating across bots, and an earlier version of
    // this comment wrongly claimed it did: each bot LOADS the shared count and
    // increments from there, so five bodies reach the four-failure block
    // threshold in four TOTAL failures rather than four each.
    //
    // That is the correct hive semantics and it is the whole hypothesis --
    // a hive learns faster and is wrong faster. It is stated here because the
    // difference between "max on merge" and "does not accumulate" is exactly
    // the kind of thing that gets read off a comment instead of measured.
    for (const [k, mine] of Object.entries(this.data.avoid ?? {})) {
      const theirs = cur.avoid[k]
      if (!theirs) {
        cur.avoid[k] = this.touched.has(k)
          ? { ...mine, reporters: [config.bot.name] }
          : { ...mine }
        continue
      }
      theirs.fails = Math.max(theirs.fails ?? 0, mine.fails ?? 0)
      theirs.last = Math.max(theirs.last ?? 0, mine.last ?? 0)
      // PROVENANCE. In a hive a belief outlives the bot that formed it, and this
      // fleet has already been wrong in exactly that way -- all five bots once
      // enforced "walking home is impossible" from labels the system itself
      // manufactured. When one bot's mistake becomes five bots' policy, you need
      // to be able to ask WHO reported it and HOW MANY independently agreed.
      // One reporter with four failures and four reporters with one each are
      // very different evidence for the same count.
      // ONLY if this bot actually observed the failure. Merging is not
      // evidence: a first version stamped every bot that merely LOADED the file,
      // so after three bots wrote anything at all every rule claimed three
      // independent reporters. Provenance that counts readers as witnesses is
      // worse than none, because it reads as corroboration.
      if (this.touched.has(k)) {
        const who = new Set(theirs.reporters ?? [])
        who.add(config.bot.name)
        theirs.reporters = [...who].sort()
      }
      for (const [c, n] of Object.entries(mine.classes ?? {})) {
        theirs.classes = theirs.classes ?? {}
        theirs.classes[c] = Math.max(theirs.classes[c] ?? 0, n)
      }
      if (mine.where) theirs.where = mine.where
    }
    // worked: successes are cumulative across bodies -- five bots each proving
    // an action works is genuinely stronger evidence than one bot proving it.
    for (const [k, mine] of Object.entries(this.data.worked ?? {})) {
      const theirs = cur.worked[k]
      if (!theirs) { cur.worked[k] = mine; continue }
      theirs.wins = Math.max(theirs.wins ?? 0, mine.wins ?? 0)
      theirs.last = Math.max(theirs.last ?? 0, mine.last ?? 0)
    }
    // progress is per-BOT even in a hive: it is goals, not experience.
    cur.progress = cur.progress ?? {}
    cur.progress[config.bot.name] = (this.data.progress ?? {})[config.bot.name]
      ?? this.data.progress ?? {}
    cur.runs = Math.max(cur.runs ?? 0, this.data.runs ?? 0)

    try {
      fs.mkdirSync(path.dirname(this.file), { recursive: true })
      const tmp = `${this.file}.${process.pid}.tmp`
      fs.writeFileSync(tmp, JSON.stringify(cur, null, 1))
      fs.renameSync(tmp, this.file)   // atomic: peers never read a half file
      this.data = cur
      this.dirty = false
    } catch (e) {
      log('warn', 'lessons: merged write failed', { err: e.message })
    }
  }

  #load() {
    try {
      const raw = JSON.parse(fs.readFileSync(this.file, 'utf8'))
      if (raw.schema === SCHEMA) this.data = raw
      else log('warn', 'lessons: schema changed, starting fresh', { was: raw.schema })
    } catch { /* first run */ }
    this.data.runs = (this.data.runs ?? 0) + 1
    this.#prune()
    this.dirty = true
    log('info', 'lessons loaded', {
      run: this.data.runs,
      avoid: Object.keys(this.data.avoid).length,
      worked: Object.keys(this.data.worked).length,
      hazard_sites: this.data.sites.length,
    })
  }

  #prune() {
    const now = Date.now()
    for (const [k, v] of Object.entries(this.data.avoid)) {
      // Halve the count rather than dropping outright: something that failed
      // ten times last week is still weak evidence, not zero evidence.
      if (now - (v.last ?? 0) > DECAY_MS) {
        v.fails = Math.floor(v.fails / 2)
        if (v.fails < 2) delete this.data.avoid[k]
      }
    }
    for (const s of this.data.sites) {
      if (now - (s.last ?? 0) > DECAY_MS) s.count = Math.floor(s.count / 2)
    }
    this.data.sites = this.data.sites.filter(s => s.count >= 2).slice(-MAX_SITES)

    const avoid = Object.entries(this.data.avoid)
      .sort((a, b) => b[1].fails - a[1].fails).slice(0, MAX_AVOID)
    this.data.avoid = Object.fromEntries(avoid)
  }

  save() {
    if (!this.dirty) return
    // SHARED MODE MUST MERGE, NOT OVERWRITE. save() writes the whole file from
    // memory; with five bots on one file that is guaranteed lost updates --
    // A loads, B loads, A writes, B writes, A's lessons gone. The hive arm
    // would then measure how fast lessons get LOST rather than how fast beliefs
    // propagate, which is a worse bug than the one it exists to study.
    // Same read-merge-write under atomic rename that worldfacts.mjs already
    // uses for exactly this reason.
    if (this.shared) return this.#saveMerged()
    // Prune here, not only on load. MAX_AVOID was enforced once at startup, so
    // the avoid map grew unbounded for the life of a run -- Gather01 reached 42
    // entries against a cap of 40. The prompt only ever shows the worst few, so
    // this was waste rather than corruption, but a cap that holds only at
    // startup is not a cap.
    if (++this.savesSincePrune >= 25) { this.savesSincePrune = 0; this.#prune() }
    try {
      fs.mkdirSync(path.dirname(this.file), { recursive: true })
      fs.writeFileSync(this.file, JSON.stringify(this.data, null, 1))
      this.dirty = false
    } catch (e) {
      log('error', 'lessons: save failed', { err: e.message })
    }
  }

  // ------------------------------------------------------------ recording --

  /**
   * Record a failure against an action.
   *
   * `gap` names WHAT WAS MISSING, when the skill can say. It is the difference
   * between "this action does not work" and "this action was attempted before
   * its preconditions were met", and only the first deserves a counter.
   *
   * Measured: `craft oak_planks` reached 47 fails on Miner01 while every single
   * failure was `missing_ingredients` -- the bot proposing exactly the right
   * action at a moment it had no logs. The counter named the action; the
   * measurement was about the inventory. A changing gap means the agent is
   * working through a dependency chain, which is progress, not a pattern.
   */
  recordFailure(skill, args, failClass, pos, gap = null) {
    const k = key(skill, args)
    this.touched.add(k)
    const e = this.data.avoid[k] ?? { skill, args, fails: 0, classes: {} }

    // A GAP THAT MOVED IS PROGRESS. Only a gap identical to last time says the
    // agent is stuck rather than climbing. `craft diamond_pickaxe` with a gap
    // that never closes still accrues normally, which is the case that keeps
    // this from being a blanket amnesty.
    if (gap != null && e.gap != null && e.gap !== gap) {
      e.fails = 0
      e.since = Date.now()
    }
    if (gap != null) e.gap = gap

    // Wall-clock decay is measured from when the CURRENT streak started, not
    // from the last touch. Keying it to the last touch meant probation -- which
    // exists to disprove a rule -- refreshed the timestamp the decay depends on
    // every ~100s, so forgiveness of one-per-20-minutes evaluated to exactly
    // zero and the counter became a pure ratchet. The escape hatch jammed the
    // escape hatch. See failCount().
    if (this.#effective(e) <= 0) {
      e.fails = 0
      e.since = Date.now()
    }
    e.since = e.since ?? Date.now()

    e.fails++
    e.last = Date.now()
    e.classes[failClass ?? 'other'] = (e.classes[failClass ?? 'other'] ?? 0) + 1
    if (pos) e.where = { x: Math.round(pos.x), y: Math.round(pos.y), z: Math.round(pos.z) }
    this.data.avoid[k] = e
    this.dirty = true
  }

  /** Failures still standing after wall-clock forgiveness. */
  #effective(e) {
    if (!e) return 0
    const forgiven = Math.floor((Date.now() - (e.since ?? e.last ?? 0)) / FORGET_MS)
    return Math.max(0, (e.fails ?? 0) - forgiven)
  }

  /** The avoid entry behind a block, for attribution. Returns null if none. */
  entryFor(skill, args) {
    const e = this.data.avoid?.[key(skill, args)]
    if (!e) return null
    return {
      key: key(skill, args),
      fails: e.fails ?? 0,
      classes: e.classes ?? {},
      // Who OBSERVED the failures. In a hive this is the difference between
      // "this bot learned it" and "a peer learned it and this bot inherited the
      // belief" -- which is the entire question the shakedown exists to answer,
      // and which cannot be recovered later from a prose rejection message.
      reporters: e.reporters ?? null,
      last: e.last ?? null,
    }
  }

  recordSuccess(skill, args) {
    const k = key(skill, args)
    const e = this.data.worked[k] ?? { skill, args, wins: 0 }
    e.wins++; e.last = Date.now()
    this.data.worked[k] = e
    // Success is evidence against an existing avoid rule, so weaken it rather
    // than letting one old failure suppress a now-working action forever.
    if (this.data.avoid[k]) {
      this.data.avoid[k].fails--
      if (this.data.avoid[k].fails <= 0) delete this.data.avoid[k]
    }
    this.dirty = true
  }

  /** Somewhere the bot drowned, got entombed, got stuck, or died. */
  // Returns how many times THIS bot has hit this site, so the shared world
  // store can insist on personal confirmation before publishing to the fleet.
  recordHazard(kind, pos) {
    if (!pos) return 0
    const near = this.data.sites.find(s =>
      s.kind === kind && Math.hypot(s.x - pos.x, s.z - pos.z) < HAZARD_RADIUS &&
      Math.abs(s.y - pos.y) < 8)
    let count
    if (near) { near.count++; near.last = Date.now(); count = near.count }
    else {
      this.data.sites.push({
        kind, x: Math.round(pos.x), y: Math.round(pos.y), z: Math.round(pos.z),
        count: 1, last: Date.now(),
      })
      count = 1
    }
    this.dirty = true
    return count
  }

  // ------------------------------------------------------------- applying --

  /**
   * Milestone progress, carried across restarts.
   *
   * Deliberately stores what the bot GAVE UP ON and how hard it has tried --
   * never which milestones are complete. Completion is re-derived from actual
   * world state on every start, because inventory can be lost to death and a
   * restored "done" would claim work the world cannot back up. A proven-
   * unreachable goal, by contrast, stays unreachable across a restart, and
   * re-attempting it from scratch every run is exactly the forever-loop this
   * file exists to end.
   */
  getProgress() {
    const p = this.data.progress ?? {}
    return {
      attempts: p.attempts ?? {},
      skipped: p.skipped ?? [],
      // When a give-up happened, and how many times. Without these a skip is
      // permanent, which is how every bot ended up with an empty goal stack.
      skippedAt: p.skippedAt ?? {},
      skipCount: p.skipCount ?? {},
      cycle: p.cycle ?? 0,
      completions: p.completions ?? {},
    }
  }

  setProgress(attempts, skipped, skippedAt, skipCount, cycle, completions) {
    // MERGE. Assigning a fresh object here dropped the sibling `blocked` key
    // that bumpBlocked() maintains -- and since this runs after every decision,
    // it wiped the probation countdown on every cycle, silently undoing the
    // persistence it was added to provide. The counter never climbed past 1.
    const p = (this.data.progress ??= {})
    p.attempts = attempts
    p.skipped = skipped
    if (skippedAt) p.skippedAt = skippedAt
    if (skipCount) p.skipCount = skipCount
    if (cycle != null) p.cycle = cycle
    if (completions) p.completions = completions
    this.dirty = true
  }

  /**
   * Count one probation block and report the running total.
   *
   * Lives here, not in AdmissionControl, because a reconnect builds a fresh
   * controller. Scout01 reached run=12 in under an hour -- every socketClosed
   * reset an in-memory tally to zero, so a 1-in-5 probation never reached 5
   * and the block stayed permanent exactly as before the fix. Third time today
   * that a counter which had to outlive the process was kept in memory.
   */
  bumpBlocked(k) {
    const p = (this.data.progress ??= {})
    p.blocked ??= {}
    p.blocked[k] = (p.blocked[k] ?? 0) + 1
    this.dirty = true
    return p.blocked[k]
  }

  /**
   * Drop everything this bot believes about a skill whose CODE has changed.
   *
   * The learning layer remembers a world that no longer exists. Twice in one
   * night, in both directions:
   *
   *   `status` returned success for a no-op and was recorded as a win 115
   *   times. The prompt read "status worked 115x -- a reliable choice" and the
   *   fleet idled successfully. Making it a no-op stopped FUTURE reinforcement
   *   and changed nothing, because the behaviour was already written down.
   *
   *   `explore` was broken (unbounded pathfinding, aborted 15/15) and duly
   *   recorded as useless. After the fix, learned_avoid kept vetoing it -- 20
   *   minutes never chosen, while the fleet sat on the exact plateau explore
   *   exists to break. The skill worked; its reputation was from when it did
   *   not.
   *
   * A judgement about a skill is only valid for the version of the skill that
   * earned it. So: hash each skill's source, and when the hash moves, drop that
   * skill's avoid/worked/probation entries. Cache invalidation on code change,
   * which is what it always was.
   *
   * Deliberately per-skill. Editing `gather` should not cost the bot everything
   * it learned about `craft`.
   */
  /**
   * Drop judgements recorded under the old, un-normalised action key.
   *
   * The key used to be JSON.stringify over whatever the model emitted, so
   * `craft stick` accumulated separate records under five spellings that
   * differed only in a `player` argument craft does not have. Those entries are
   * unreachable once the key is normalised, and their counts are not valid
   * evidence about the normalised action anyway -- they conflate distinct
   * proposals and include arguments the skill ignores.
   *
   * Re-keying and MERGING them would be worse than dropping: it would sum five
   * partial records into one count high enough to keep the action permanently
   * blocked, which is the freeze this change exists to end.
   *
   * Idempotent -- after one pass every remaining key already equals its own
   * normalised form, so subsequent runs drop nothing.
   */
  migrateActionKeys() {
    let dropped = 0
    for (const section of ['avoid', 'worked']) {
      const store = this.data[section] ?? {}
      for (const [k, v] of Object.entries(store)) {
        if (!v?.skill) continue
        if (actionKey(v.skill, v.args) !== k) { delete store[k]; dropped++ }
      }
    }
    if (dropped) { this.dirty = true; log('info', 'dropped judgements under the old action key', { dropped }) }
    return dropped
  }

  reconcileSkillVersions(skills) {
    const now = {}
    for (const [name, def] of Object.entries(skills)) {
      const src = String(def?.run ?? '')
      let h = 5381
      for (let i = 0; i < src.length; i++) h = ((h * 33) ^ src.charCodeAt(i)) >>> 0
      now[name] = h.toString(36)
    }

    const previous = this.data.skillVersions ?? {}
    const changed = Object.keys(now).filter(n => previous[n] && previous[n] !== now[n])

    for (const name of changed) {
      const before = Object.keys(this.data.avoid).length + Object.keys(this.data.worked).length
      this.data.avoid = Object.fromEntries(
        Object.entries(this.data.avoid).filter(([, v]) => v.skill !== name))
      this.data.worked = Object.fromEntries(
        Object.entries(this.data.worked).filter(([, v]) => v.skill !== name))
      if (this.data.progress?.blocked) {
        this.data.progress.blocked = Object.fromEntries(
          Object.entries(this.data.progress.blocked).filter(([k]) => !k.startsWith(`${name}:`)))
      }
      const after = Object.keys(this.data.avoid).length + Object.keys(this.data.worked).length
      log('info', 'skill changed, clearing what was learned about it', {
        skill: name, entries_dropped: before - after,
      })
    }

    this.data.skillVersions = now
    if (changed.length) this.dirty = true
    return changed
  }

  /** How many times this exact action has failed, across ALL runs. */
  failCount(skill, args) {
    const e = this.data.avoid[key(skill, args)]
    if (!e) return 0
    // Failures DECAY. Without this the count only ever rises, so the gate could
    // do nothing over a long run but tighten -- which is what happened: the
    // fleet's veto rate climbed 23% -> 72% across sixteen hours, until three
    // quarters of every decision was rejected before it could execute and the
    // bots stood still while the model kept proposing the actions their own
    // milestones required.
    //
    // The world is not static. Terrain gets mined, inventories fill, a tree
    // grows within reach. Evidence that `gather oak_log` failed eleven times
    // this morning says very little about whether it works now, and an action
    // nobody has attempted in an hour deserves to be tried again.
    //
    // Forgiveness runs from `since` -- when the current failure streak STARTED
    // -- not from `last`, when it was most recently touched. Using `last` made
    // decay unreachable for exactly the rules that needed it: probation retries
    // a blocked action every ~100s, each retry refreshed `last`, and
    // floor(100s / 20min) is 0. Counters reached 47 and 54 with a forgiveness
    // rate of precisely nothing. A rule now ages out on wall-clock whether or
    // not the bot keeps bumping into it.
    return this.#effective(e)
  }

  /** Hazard sites within range of a point, worst first. */
  hazardsNear(pos, radius = 40) {
    if (!pos) return []
    return this.data.sites
      .filter(s => Math.hypot(s.x - pos.x, s.z - pos.z) <= radius && s.count >= 2)
      .sort((a, b) => b.count - a.count)
  }

  /**
   * The lines injected into the prompt. Kept short and concrete -- a wall of
   * history crowds out current world state, which is worth more.
   */
  promptLines(pos, limit = 6) {
    const out = []
    const worst = Object.values(this.data.avoid)
      .filter(e => e.fails >= 2)
      .sort((a, b) => b.fails - a.fails)
      .slice(0, limit)
    for (const e of worst) {
      const why = Object.entries(e.classes).sort((a, b) => b[1] - a[1])[0]?.[0] ?? 'failed'
      out.push(`${e.skill}(${JSON.stringify(e.args)}) has failed ${e.fails}x across runs — usually "${why}"`)
    }
    for (const s of this.hazardsNear(pos, 60).slice(0, 3)) {
      out.push(`${s.kind} happened ${s.count}x near ${s.x},${s.y},${s.z} — avoid that area`)
    }
    const best = Object.values(this.data.worked)
      .filter(e => e.wins >= 3).sort((a, b) => b.wins - a.wins).slice(0, 2)
    for (const e of best) {
      out.push(`${e.skill}(${JSON.stringify(e.args)}) has worked ${e.wins}x — a reliable choice`)
    }
    return out
  }

  get stats() {
    return {
      run: this.data.runs,
      avoid: Object.keys(this.data.avoid).length,
      worked: Object.keys(this.data.worked).length,
      sites: this.data.sites.length,
    }
  }
}

// ONE instance per process. openLessons() is called from the spawn handler,
// which runs again on every reconnect -- so this used to build a second Lessons
// object that re-read the file while the running cognitive loop still held the
// first. Whichever saved last won, and anything the old instance had in memory
// but not yet flushed was erased.
//
// Measured: Scout01 (run=18, the most reconnects in the fleet) had four
// recorded successes in Elasticsearch -- 21:53, 22:11, 22:19, 23:20 -- and a
// `worked` map on disk of exactly {}. Its successes were being deleted by its
// own reconnects, which is why it looked like it had never once succeeded.
//
// This also makes `runs` mean what it claims: process starts, not reconnects.
let instance = null

export function openLessons() {
  if (instance) return instance
  // MEMORY_SCOPE=shared puts every bot on one file; isolated and private both
  // keep a bot's failures to itself. See config.memory for what each means.
  const shared = config.memory.scope === 'shared'
  const name = shared ? 'lessons-hive.json' : `lessons-${config.bot.name}.json`
  instance = new Lessons(path.join(config.log.stateDir, name), shared)
  return instance
}
