- resources:
    label: mcai
    cpu: true
    memory: true
    disk: /srv/minecraft
- search:
    provider: duckduckgo
    target: _blank
- datetime:
    text_size: xl
    format:
      dateStyle: short
      timeStyle: short
      hourCycle: h23
